export const categoryIcons: Record<string, string> = {
  'actor': '🎭',
  'actress': '🎭',
  'singer': '🎤',
  'musician': '🎵',
  'sportsman': '⚽',
  'sportswoman': '🏃‍♀️',
  'internet-celebrity': '🌐',
  'dancer': '💃',
  'entrepreneur': '💼',
  'comedian': '😂',
  'model': '📸',
  'influencer': '📱',
  'youtuber': '📺',
  'streamer': '🎮',
  'politician': '🏛️',
  'business': '💼',
  'scientist': '🔬',
  'writer': '✍️',
  'director': '🎬',
  'producer': '🎥',
  'tv-host': '📺',
  'chef': '👨‍🍳',
  'rapper': '🎵',
  'footballer': '⚽',
  'tennis-player': '🎾',
  'basketball-player': '🏀',
  'golfer': '⛳',
  'gymnast': '🤸'
};

export const categoryLabels: Record<string, string> = {
  'actor': 'Actor',
  'actress': 'Actress',
  'singer': 'Singer',
  'musician': 'Musician',
  'sportsman': 'Sportsman',
  'sportswoman': 'Sportswoman',
  'internet-celebrity': 'Internet Celebrity',
  'dancer': 'Dancer',
  'entrepreneur': 'Entrepreneur',
  'comedian': 'Comedian',
  'model': 'Model',
  'influencer': 'Influencer',
  'youtuber': 'YouTuber',
  'streamer': 'Streamer',
  'politician': 'Politician',
  'business': 'Business',
  'scientist': 'Scientist',
  'writer': 'Writer',
  'director': 'Director',
  'producer': 'Producer',
  'tv-host': 'TV Host',
  'chef': 'Chef',
  'rapper': 'Rapper',
  'footballer': 'Footballer',
  'tennis-player': 'Tennis Player',
  'basketball-player': 'Basketball Player',
  'golfer': 'Golfer',
  'gymnast': 'Gymnast'
};
